# Welcome to Jekyll!
#

# Site settings
title: "Hélène Wang"
description: |
  Site web de Hélène Wang
owner: "Hélène Wang"
first_published: 2017 # if migrating another site, the year of your first publish
email: info@helene-wang.fr
baseurl: "" # the subpath of your site, e.g. /blog
path: "http://helene-wang.fr" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/helene-wang
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: "mailto:info@helene-wang.fr"
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

plugins:
  - jekyll-polyglot
languages: ["fr", "en", "it"]
default_lang: "fr"
exclude_from_localization: ["audio", "css", "fonts", "images", "js"]
parallel_localization: true

exclude:
  - upload.sh
  - login.sh
  - LICENSE.txt
  - README.txt
